version: '2.3'

services:
  kubeflow-component:
    image: docker.io/cyferino/component-kubeflow:0.0.14
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    volumes:
      - ./src:/src
      - ./data:/mnt
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  